### PR TITLE
Some missing translations and a fix for beds translation

### PR DESCRIPTION
**Pull request by Xanthin**
Solution for the issue with cotton and wheat in farming is still needed.

### CODE REVIEW

**Comment by Adimgar** [comment]
Perfect! thank you so much @Xanthin

**Comment by Xanthin** [comment]
Oh, thank _you_ very much that you started it.
I am a bit unsure when and where I should push the german files. Maybe when your PR got merged?
Btw. did you tried downloading your translated repo and looking for the translated words? You'll maybe see that any non-us character is messed up. I know this from when I used german umlauts.
For example: your 
Coal Lump = Bulto de carbón
might be
Coal Lump = Bulto de carbÃ³n
then.
This can be fixed in the local copy and will be displayed correct again. I don't know why this happen.
Or maybe this happens only to me?

**Comment by Adimgar** [comment]
Well, since I have all my environment language set to es_MX.utf8 I can get non-us and latin characters displayed correctly, I've tested the translations in my local server and they are displayed correctly, since the es.txt langfiles will be loaded by Intllib when the server is started on a spanish environment, I believe (hope) it'll work. Have you tryied adding your german translations locally and see if they are displayed correctly?
About when to push your translations, I think you can do it whenever you want in this branch, because I'm still not sure if it'll be merged at all, but I can merge your translations in this branch as soon as you push them if it's ok to you.

**Comment by Adimgar** [comment]
> Solution for the issue with cotton and wheat in farming is still needed.

I know, but I haven't been able to approach to a fix, let me get more familiar with lua and the mods mechanics and see if I can fix it, I'm barely starting on this :D. I haven't found their description nor figured out where they come from.

**Comment by Xanthin** [comment]
Just quick, I found a solution. But I don't have a clue how I can have my copy of your updated translation branch even and push there the change I made and create a pr from there _without_ messing up the history. And I am too much tired to have another night with the git manual. Sorry.
Maybe you want to look in my repository for the update and test if it works for you too and if it is okay. Then you can paste it in your copy and everything looks nice. :)
https://github.com/Xanthin/minetest_game/commit/1506a239ca7f1d8427bf979502265920611067fb

Btw. this translation stuff was also what got me started to look into the mods and lua things a while ago. ;) Can't say I made much progress but it makes fun.

**Comment by Adimgar** [comment]
That's great, but I don't realy understand how it works, if you have time, look for me tomorrow on IRC #minetest channel between 9:00 - 16:00 UTC-6 and talk about yout fix and I'll assist you with pushing and pulling your branch :)
And yes, big things starts from small things. In my case, a pretty small person, I got here because of my daughter, it's a nice story ;) it's always fun to learn new things.

**Comment by Xanthin** [comment]
Okay, I will. I think I figured out how to do this IRC thing, hopefully. :)
But don't expect too much, I am not a programmer or something related. There are a lot and much more advanced people around. I just do some heuristic and reading.

**Comment by Xanthin** [comment]
You have mail.

**Pull request merged**
